export default function page() {
  return (
    <div>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
      <h1>This is vacation page</h1>
    </div>
  );
}
